Repository UPEI-Android/virtual-wellness-project, pull requests merged in 2022-03, with the labels that each got.

#101 Shi rules schema
  app/Http/Controllers/RulesController.php
  app/Http/Controllers/TreatmentController.php
  app/Http/Requests/TreatmentRequest.php
  app/Models/RecurringPattern.php
  app/Models/Rule.php
  app/Models/Treatment.php
  app/Models/TreatmentTask.php
  app/Models/User.php
  app/Traits/SelfReferenceTrait.php
  composer.json
  composer.lock
  database/factories/RuleFactory.php
  database/factories/TreatmentFactory.php
  database/migrations/2022_02_14_155617_create_treatment_tasks_table.php
  database/migrations/2022_02_14_160949_create_recurring_types_table.php
  database/migrations/2022_02_14_161146_create_recurring_patterns_table.php
  database/migrations/2022_02_28_015325_create_treatments_table.php
  database/migrations/2022_03_16_084941_create_rules_table.php
  routes/api.php
  tests/Feature/ManagingTreatmentTest.php
  tests/Feature/RulesTest.php
  tests/Feature/TreatmentTest.php
Labels: enhancement

#106 Liz individual treatment add attributes
  app/Http/Controllers/Auth/RegisterController.php
  app/Models/User.php
  resources/views/auth/register.blade.php
  resources/views/layouts/app.blade.php
  resources/views/users/userprofile.blade.php
Labels: complete

#104 Major deployment fixes and Sanctum
  .github/workflows/upstream-sync.yml
  app/Http/Controllers/UserController.php
  app/Http/Kernel.php
  app/Models/User.php
  composer.json
  composer.lock
  config/cors.php
  config/session.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2019_12_14_000001_create_personal_access_tokens_table copy.php
  database/seeders/DatabaseSeeder.php
  resources/js/bootstrap.jsx
  routes/api.php
  routes/web.php
Labels: bug, enhancement, major fix

#114 Users attached to treatment with auth
  app/Http/Controllers/TreatmentController.php
  app/Models/User.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2019_12_14_000001_create_personal_access_tokens_table copy.php
  routes/api.php
  tests/Feature/ManagingTreatmentTest.php
  tests/Feature/RulesTest.php
  tests/Feature/TreatmentCompletedTest.php
  tests/Feature/TreatmentTest.php
  tests/Unit/UserTest.php
Labels: enhancement

#120 Liz connecting
  public/js/app.js
  resources/js/app.jsx
  resources/js/components/SideBar/NavItem.jsx
  resources/js/components/SideBar/SideBarNav.jsx
  resources/js/components/Treatment/TreatmentFilters.jsx
  resources/js/components/Treatment/TreatmentForm.jsx
  resources/js/components/Treatment/TreatmentList.jsx
  resources/js/components/Treatment/TreatmentListCopy.jsx
  resources/js/components/Treatment/TreatmentOverview.jsx
  resources/js/components/Treatment/TreatmentOverviewContainer.jsx
  resources/js/components/Treatment/noTreatments.jsx
  resources/js/components/store/actions/TreatmentActions.js
  resources/js/components/store/reducers/TreatmentReducer.js
  resources/js/hooks/useFetch.js
  resources/views/treatmentViews/indexOfTreatments.blade.php
  routes/api.php
  routes/web.php
Labels: complete

#117 Rules Service created
  app/Http/Controllers/TreatmentController.php
  app/Services/RulesService.php
  database/factories/RuleFactory.php
  tests/Feature/RulesParsingTest.php
Labels: enhancement
